"""
layout_gen.synth.ml.fix_policy — DRC violation fix predictor.

Provides an ML-guided iterative repair loop for the synthesizer:

1. Build a layout.
2. Run DRC → list of :class:`~layout_gen.drc.base.DRCViolation`.
3. :class:`DRCFixPredictor` predicts parameter deltas that should fix them.
4. Apply deltas, clamp to PDK minimums, repeat.

Training uses analytical violation/fix pairs generated by
:func:`generate_fix_dataset` — no real DRC tool is required for training.
For each rule, we sweep parameter values into the violating region and record
the minimum delta that restores compliance.

The encoder is **category-based** — it does not depend on PDK-specific rule
names.  Violations are grouped by category (spacing, width, enclosure, area,
etc.) and layer class (gate, diff, contact, metal, via, well, interconnect).
This lets a model trained on sky130A data generalise to TSMC 65nm/180nm or
any other CMOS process with the same physical violation types.

Optimisation params (and their delta keys)
------------------------------------------
``"w_N"``, ``"w_P"``, ``"l"``, ``"gap_y"``, ``"finger_N"``, ``"finger_P"``

Usage::

    from layout_gen import load_pdk
    from layout_gen.synth.ml.fix_policy import DRCFixPredictor, generate_fix_dataset

    rules   = load_pdk()
    dataset = generate_fix_dataset(rules, n_samples=10_000)
    pred    = DRCFixPredictor()
    pred.fit(dataset.X, dataset.y)

    # In the synthesizer loop:
    delta   = pred.predict(violations, current_params)
    new_params = {k: current_params[k] + delta.get(k, 0) for k in current_params}
"""
from __future__ import annotations

import re
from typing import NamedTuple

import numpy as np

from layout_gen.pdk            import PDKRules
from layout_gen.cells.standard import _inter_cell_gap
from layout_gen.synth.ml.features import (
    MARGIN_NAMES, drc_margins, _geom_override_fingers,
)
from layout_gen.transistor import transistor_geom

# ── Known rules (must match MARGIN_NAMES order) ────────────────────────────────

_PARAM_NAMES: list[str] = ["w_N", "w_P", "l", "gap_y", "finger_N", "finger_P"]

# Per rule: which param index is the primary fix lever
# Index into _PARAM_NAMES
_RULE_FIX_PARAM: dict[str, int] = {
    "poly.1":     2,  # l
    "diff.1_N":   0,  # w_N
    "diff.1_P":   1,  # w_P
    "licon.5a_N": 0,  # w_N (sd_length fixed in sky130A; increasing w helps indirectly)
    "licon.5a_P": 1,  # w_P
    "licon.7_N":  0,  # w_N
    "licon.7_P":  1,  # w_P
    "diff.2":     3,  # gap_y
    "nwell.1":    1,  # w_P
    "li1.1":      0,  # w_N
    "li1.2":      2,  # l  (li1 gap across gate = gate length; increase l)
    "poly.2":     3,  # gap_y  (increase device spacing via inter-cell gap)
}

# Tiny headroom added on top of rule boundary when computing fix delta
_EPS = 0.005   # µm


# ── Category-based violation encoding (PDK-agnostic) ─────────────────────────

# Violation categories — same set used by geo.violations.ViolationInfo
VIOLATION_CATEGORIES: list[str] = [
    "spacing", "width", "enclosure", "area",
    "overlap", "extension", "offgrid", "size", "unknown",
]

# Layer classes — abstract away PDK-specific layer names
LAYER_CLASSES: list[str] = [
    "gate",          # poly
    "diffusion",     # diff, active, OD
    "contact",       # licon1, CO
    "interconnect",  # li1, local interconnect
    "metal1",        # met1, M1
    "metal2",        # met2, M2
    "via",           # via1, via2, V1
    "well",          # nwell, pwell
    "implant",       # nsdm, psdm, nplus, pplus
    "other",
]

_LAYER_TO_CLASS: dict[str, str] = {
    "poly": "gate", "gate": "gate", "pc": "gate",
    "diff": "diffusion", "active": "diffusion", "od": "diffusion",
    "licon1": "contact", "mcon": "contact", "contact": "contact", "co": "contact",
    "li1": "interconnect", "li": "interconnect",
    "met1": "metal1", "m1": "metal1", "metal1": "metal1",
    "met2": "metal2", "m2": "metal2", "metal2": "metal2",
    "met3": "metal2",  # higher metals grouped with metal2
    "via1": "via", "via2": "via", "v1": "via", "v2": "via",
    "nwell": "well", "pwell": "well",
    "nsdm": "implant", "psdm": "implant", "nplus": "implant", "pplus": "implant",
}


def _classify_layer(layer: str) -> str:
    """Map a PDK-specific layer name to an abstract layer class."""
    return _LAYER_TO_CLASS.get(layer.lower().strip(), "other")


def _classify_category(rule: str, desc: str) -> str:
    """Classify a violation by category from rule name and description.

    Mirrors the logic in geo.violations but returns our encoding categories.
    """
    text = f"{rule} {desc}".lower()
    if re.search(r"size\b|\.1\b.*size", text) and re.search(r"licon|mcon|co\b|via", text):
        return "size"
    if re.search(r"spacing|space|\.sp\b", text):
        return "spacing"
    if re.search(r"width|\.w\b|minimum width", text):
        return "width"
    if re.search(r"enclos|ovlp|overlap.*encl", text):
        return "enclosure"
    if re.search(r"area\b|min.*area", text):
        return "area"
    if re.search(r"overlap|short|bridg", text):
        return "overlap"
    if re.search(r"extend|extension|endcap", text):
        return "extension"
    if re.search(r"off.?grid|grid", text):
        return "offgrid"
    return "unknown"


# ── Violation encoder ──────────────────────────────────────────────────────────

class ViolationEncoder:
    """Encode DRC violations + params into a fixed-length feature vector.

    The encoding is **PDK-agnostic**: violations are binned by
    (category × layer_class) rather than by PDK-specific rule name.

    Feature vector layout (N_CAT*N_LAYER + N_PARAMS + 3 floats):
    - ``[0:N_CAT*N_LAYER]`` — violation deficit summed per
      (category, layer_class) bin.  9 categories × 10 layers = 90 bins.
    - ``[90:96]``  — current parameter values.
    - ``[96:98]``  — centroid (x_mean, y_mean) of violations.
    - ``[98]``     — total violation count.
    - ``[99:111]`` — analytical margin deficits (legacy, for backward compat
      with sky130A-trained models; zeros for other PDKs).
    """

    N_CATEGORIES = len(VIOLATION_CATEGORIES)  # 9
    N_LAYERS     = len(LAYER_CLASSES)          # 10
    N_BINS       = N_CATEGORIES * N_LAYERS     # 90
    N_PARAMS     = len(_PARAM_NAMES)           # 6
    N_MARGINS    = len(MARGIN_NAMES)           # 12
    FEATURE_DIM  = N_BINS + N_PARAMS + 3 + N_MARGINS  # 111

    _cat_idx   = {c: i for i, c in enumerate(VIOLATION_CATEGORIES)}
    _layer_idx = {c: i for i, c in enumerate(LAYER_CLASSES)}

    def encode(
        self,
        violations: list,   # list[DRCViolation]
        params:     dict,
        rules:      PDKRules,
    ) -> np.ndarray:
        """Return a feature vector describing *violations* and *params*."""
        vec = np.zeros(self.FEATURE_DIM, dtype=np.float64)

        # ── Category × layer bins from actual violations ──
        for v in violations:
            rule = getattr(v, "rule", "")
            desc = getattr(v, "description", "") or ""
            cat = _classify_category(rule, desc)
            layer = _classify_layer(
                _extract_layer_from_rule_name(rule))
            ci = self._cat_idx.get(cat, self._cat_idx["unknown"])
            li = self._layer_idx.get(layer, self._layer_idx["other"])
            # Use measured deficit or default 0.01
            deficit = 0.01
            measured = getattr(v, "value", None)
            if measured is not None and measured > 0:
                req = _extract_required_from_desc(desc)
                if req > 0:
                    deficit = max(0.01, req - measured)
            vec[ci * self.N_LAYERS + li] += deficit

        # ── Current param values ──
        off = self.N_BINS
        for i, pname in enumerate(_PARAM_NAMES):
            vec[off + i] = float(params.get(pname, 0.0))

        # ── Spatial centroid ──
        off2 = self.N_BINS + self.N_PARAMS
        if violations:
            xs = [v.x for v in violations if hasattr(v, "x")]
            ys = [v.y for v in violations if hasattr(v, "y")]
            vec[off2]     = float(np.mean(xs)) if xs else 0.0
            vec[off2 + 1] = float(np.mean(ys)) if ys else 0.0
        vec[off2 + 2] = float(len(violations))

        # ── Analytical margins (sky130A compat) ──
        off3 = self.N_BINS + self.N_PARAMS + 3
        try:
            margins = drc_margins(
                float(params.get("w_N",      0.52)),
                float(params.get("w_P",      0.42)),
                float(params.get("l",         0.15)),
                rules,
                gap_y    = float(params.get("gap_y",    _inter_cell_gap(rules))),
                finger_N = float(params.get("finger_N", 1.0)),
                finger_P = float(params.get("finger_P", 1.0)),
            )
            vec[off3:off3 + self.N_MARGINS] = np.maximum(0.0, -margins)
        except Exception:
            pass

        return vec


def _extract_layer_from_rule_name(rule: str) -> str:
    """Extract primary layer from rule name like 'met2.1' or 'licon.5a'."""
    parts = rule.strip().strip("'\"").split(".", 1)
    return parts[0] if parts else ""


def _extract_required_from_desc(desc: str) -> float:
    """Extract required dimension from violation description."""
    m = re.search(r'(?:[:<>=]|by)\s*(\d+\.?\d*)\s*(?:um|µm)', desc, re.I)
    if m:
        return float(m.group(1))
    return 0.0


# ── Fix dataset ────────────────────────────────────────────────────────────────

class FixDataset(NamedTuple):
    """Training dataset for :class:`DRCFixPredictor`.

    Attributes
    ----------
    X :
        Violation-encoded feature matrix, shape ``(N, FEATURE_DIM)``.
        FEATURE_DIM = 111 (90 category×layer bins + 6 params + 3 spatial + 12 margins).
    y :
        Parameter delta matrix, shape ``(N, 6)``.
        Column order matches :data:`_PARAM_NAMES`.
    """
    X: np.ndarray
    y: np.ndarray


def generate_fix_dataset(
    rules:     PDKRules,
    n_samples: int = 10_000,
    seed:      int = 42,
) -> FixDataset:
    """Generate analytical violation→fix-delta training pairs.

    For each sample we draw a parameter vector, compute the analytical DRC
    margins, and for each violated rule calculate the minimum delta in the
    primary fix parameter that would bring the margin back to zero.
    The resulting deltas form the regression target ``y``.

    Parameters
    ----------
    rules :
        PDK rules.
    n_samples :
        Number of parameter samples to draw.
    seed :
        NumPy RNG seed.

    Returns
    -------
    FixDataset
    """
    rng = np.random.default_rng(seed)
    enc = ViolationEncoder()

    gap_min = _inter_cell_gap(rules)
    poly_wmin = rules.poly["width_min_um"]
    diff_wmin = rules.diff["width_min_um"]
    c_size    = rules.contacts["size_um"]
    c_enc     = rules.contacts["enclosure_in_diff_um"]
    stp       = rules.contacts["space_to_poly_um"]
    li1_wmin  = rules.li1["width_min_um"]
    nw_enc    = rules.nwell["enclosure_of_pdiff_um"]
    nw_wmin   = rules.nwell["width_min_um"]

    # Sample params biased toward the violating region
    w_N_arr    = rng.uniform(0.08, 0.60, n_samples)
    w_P_arr    = rng.uniform(0.08, 0.60, n_samples)
    l_arr      = rng.uniform(0.08, 0.40, n_samples)
    gap_y_arr  = rng.uniform(0.00, gap_min * 3, n_samples)
    fn_arr     = rng.integers(1, 5, n_samples)
    fp_arr     = rng.integers(1, 5, n_samples)

    X_rows: list[np.ndarray] = []
    y_rows: list[np.ndarray] = []

    for w_N, w_P, l, gap_y, fn, fp in zip(
        w_N_arr, w_P_arr, l_arr, gap_y_arr, fn_arr, fp_arr
    ):
        try:
            margins = drc_margins(
                w_N, w_P, l, rules,
                gap_y=float(gap_y), finger_N=float(fn), finger_P=float(fp),
            )
        except Exception:
            continue

        # Only use samples that have at least one violation
        if np.all(margins >= 0):
            continue

        params = {
            "w_N":      w_N,
            "w_P":      w_P,
            "l":        l,
            "gap_y":    float(gap_y),
            "finger_N": float(fn),
            "finger_P": float(fp),
        }

        # Compute minimum-delta fix for each violated rule
        delta = np.zeros(len(_PARAM_NAMES), dtype=np.float64)

        ng_base = transistor_geom(w_N, l, "nmos", rules)
        pg_base = transistor_geom(w_P, l, "pmos", rules)
        ng = _geom_override_fingers(ng_base, int(fn), rules)
        pg = _geom_override_fingers(pg_base, int(fp), rules)

        for rule_idx, (rule_name, margin) in enumerate(zip(MARGIN_NAMES, margins)):
            if margin >= 0:
                continue
            # deficit = amount the param must change
            deficit = -margin + _EPS
            p_idx = _RULE_FIX_PARAM[rule_name]

            if rule_name == "poly.1":
                # l → increase l
                delta[p_idx] = max(delta[p_idx], deficit)

            elif rule_name == "diff.1_N":
                # w_finger_N = w_N / fn → must reach diff_wmin
                # delta_w_N = deficit * fn
                delta[p_idx] = max(delta[p_idx], deficit * fn)

            elif rule_name == "diff.1_P":
                delta[p_idx] = max(delta[p_idx], deficit * fp)

            elif rule_name in ("licon.5a_N", "licon.7_N", "li1.1"):
                # sd_length is fixed by PDK min; can't fix via params analytically.
                # Widen w_N so transistor_geom recalculates (sd_length is constant
                # in sky130A, so this signals the model to try widening).
                delta[p_idx] = max(delta[p_idx], deficit)

            elif rule_name in ("licon.5a_P", "licon.7_P"):
                delta[p_idx] = max(delta[p_idx], deficit)

            elif rule_name == "diff.2":
                # gap_y → increase gap_y by deficit
                delta[p_idx] = max(delta[p_idx], deficit)

            elif rule_name == "nwell.1":
                # nwell_x_width = total_x_P + 2*nw_enc >= nw_wmin
                # total_x_P = (fp+1)*sd + fp*l  → fix via w_P (changes total_y only, not x)
                # Actually nwell.1 is about X-width of nwell; to increase total_x_P
                # we need more fingers or wider device. Fix via increasing fp:
                # If fp < 4: suggest fp+1 (which increases total_x_P by sd+l)
                # Otherwise widen w_P.
                if fp < 4:
                    delta[5] = max(delta[5], 1.0)  # finger_P += 1
                else:
                    delta[p_idx] = max(delta[p_idx], deficit)

            elif rule_name == "li1.2":
                # li1 spacing across gate = l.  Need l >= li1_spacing_min.
                # Increase l by deficit.
                delta[p_idx] = max(delta[p_idx], deficit)

            elif rule_name == "poly.2":
                # Poly spacing between adjacent devices depends on diff spacing.
                # When diff_spacing < poly_spacing_min, increase gap_y to push
                # devices further apart.
                delta[p_idx] = max(delta[p_idx], deficit)

        # Skip if no deltas were computed (shouldn't happen)
        if not np.any(delta > 0):
            continue

        feat = enc.encode([], params, rules)  # no live DRC violations (analytical)
        X_rows.append(feat)
        y_rows.append(delta)

    X = np.array(X_rows, dtype=np.float64)
    y = np.array(y_rows, dtype=np.float64)
    return FixDataset(X=X, y=y)


# ── DRC fix predictor ──────────────────────────────────────────────────────────

class DRCFixPredictor:
    """MLP that maps violation features → parameter deltas.

    Parameters
    ----------
    hidden_layer_sizes :
        Sizes of hidden layers in the MLP (passed to
        ``sklearn.neural_network.MLPRegressor``).

    Usage::

        pred = DRCFixPredictor()
        pred.fit(dataset.X, dataset.y)
        delta = pred.predict(violations, params)
        # delta is {param_name: delta_value, ...}
    """

    def __init__(self, hidden_layer_sizes: tuple[int, ...] = (64, 32)):
        self.hidden_layer_sizes = hidden_layer_sizes
        self._mlp = None
        self._encoder = ViolationEncoder()

    def fit(self, X: np.ndarray, y: np.ndarray) -> "DRCFixPredictor":
        """Train the MLP on violation-encoding → delta pairs.

        Parameters
        ----------
        X :
            Feature matrix from :func:`generate_fix_dataset`, shape ``(N, FEATURE_DIM)``.
        y :
            Delta matrix, shape ``(N, 6)``.

        Returns
        -------
        self
        """
        try:
            from sklearn.neural_network import MLPRegressor
            from sklearn.preprocessing  import StandardScaler
            from sklearn.pipeline       import Pipeline
        except ImportError as exc:
            raise ImportError(
                "scikit-learn is required to train DRCFixPredictor.  "
                "Install it with: pip install scikit-learn"
            ) from exc

        self._mlp = Pipeline([
            ("scaler", StandardScaler()),
            ("mlp",    MLPRegressor(
                hidden_layer_sizes=self.hidden_layer_sizes,
                max_iter=500,
                random_state=42,
            )),
        ])
        self._mlp.fit(X, y)
        return self

    def predict(
        self,
        violations: list,   # list[DRCViolation]
        params:     dict,
        rules:      PDKRules,
    ) -> dict[str, float]:
        """Predict parameter deltas that should fix *violations*.

        Parameters
        ----------
        violations :
            DRC violations from the last synthesis attempt.
        params :
            Current parameter dict.
        rules :
            PDK rules (used for analytical margin recomputation).

        Returns
        -------
        dict[str, float]
            Map of ``param_name → delta``.  Zero for params not needing change.
            Returns zeros for all params if the model is not trained.
        """
        if self._mlp is None:
            return {p: 0.0 for p in _PARAM_NAMES}

        feat = self._encoder.encode(violations, params, rules)
        delta_vec = self._mlp.predict(feat.reshape(1, -1))[0]

        # Clamp deltas to non-negative (we only fix, never shrink)
        delta_vec = np.maximum(0.0, delta_vec)

        result: dict[str, float] = {}
        for i, pname in enumerate(_PARAM_NAMES):
            val = float(delta_vec[i])
            if val != 0.0:
                result[pname] = val
        return result

    @property
    def is_trained(self) -> bool:
        """True if the predictor has been fitted."""
        return self._mlp is not None

    def __repr__(self) -> str:
        status = "trained" if self.is_trained else "not trained"
        return f"DRCFixPredictor(hidden={self.hidden_layer_sizes}, {status})"
