"""
layout_gen.synth.ml.fix_policy — DRC violation fix predictor.

Provides an ML-guided iterative repair loop for the synthesizer:

1. Build a layout.
2. Run DRC → list of :class:`~layout_gen.drc.base.DRCViolation`.
3. :class:`DRCFixPredictor` predicts parameter deltas that should fix them.
4. Apply deltas, clamp to PDK minimums, repeat.

Training uses analytical violation/fix pairs generated by
:func:`generate_fix_dataset` — no real DRC tool is required for training.
For each rule, we sweep parameter values into the violating region and record
the minimum delta that restores compliance.

Optimisation params (and their delta keys)
------------------------------------------
``"w_N"``, ``"w_P"``, ``"l"``, ``"gap_y"``, ``"finger_N"``, ``"finger_P"``

Usage::

    from layout_gen import load_pdk
    from layout_gen.synth.ml.fix_policy import DRCFixPredictor, generate_fix_dataset

    rules   = load_pdk()
    dataset = generate_fix_dataset(rules, n_samples=10_000)
    pred    = DRCFixPredictor()
    pred.fit(dataset.X, dataset.y)

    # In the synthesizer loop:
    delta   = pred.predict(violations, current_params)
    new_params = {k: current_params[k] + delta.get(k, 0) for k in current_params}
"""
from __future__ import annotations

from typing import NamedTuple

import numpy as np

from layout_gen.pdk            import PDKRules
from layout_gen.cells.standard import _inter_cell_gap
from layout_gen.synth.ml.features import (
    MARGIN_NAMES, drc_margins, _geom_override_fingers,
)
from layout_gen.transistor import transistor_geom

# ── Known rules (must match MARGIN_NAMES order) ────────────────────────────────

_PARAM_NAMES: list[str] = ["w_N", "w_P", "l", "gap_y", "finger_N", "finger_P"]

# Per rule: which param index is the primary fix lever
# Index into _PARAM_NAMES
_RULE_FIX_PARAM: dict[str, int] = {
    "poly.1":     2,  # l
    "diff.1_N":   0,  # w_N
    "diff.1_P":   1,  # w_P
    "licon.5a_N": 0,  # w_N (sd_length fixed in sky130A; increasing w helps indirectly)
    "licon.5a_P": 1,  # w_P
    "licon.7_N":  0,  # w_N
    "licon.7_P":  1,  # w_P
    "diff.2":     3,  # gap_y
    "nwell.1":    1,  # w_P
    "li1.1":      0,  # w_N
}

# Tiny headroom added on top of rule boundary when computing fix delta
_EPS = 0.005   # µm


# ── Violation encoder ──────────────────────────────────────────────────────────

class ViolationEncoder:
    """Encode a list of DRC violations + current params into a fixed-length vector.

    Feature vector layout (31 floats):
    - ``[0:10]``  — rule indicator: sum over violations of ``-margin``
                   for each of the 10 MARGIN_NAMES (≥ 0 when violated).
    - ``[10:16]`` — current parameter values (w_N, w_P, l, gap_y, finger_N, finger_P).
    - ``[16:18]`` — centroid of violating geometry (x_mean, y_mean), µm.
    - ``[18]``    — number of violations (scalar).
    """

    N_RULES    = len(MARGIN_NAMES)   # 10
    N_PARAMS   = len(_PARAM_NAMES)   # 6
    FEATURE_DIM = N_RULES + N_PARAMS + 2 + 1  # = 19... no: 10+6+2+1 = 19

    def encode(
        self,
        violations: list,   # list[DRCViolation]
        params:     dict,
        rules:      PDKRules,
    ) -> np.ndarray:
        """Return a (19,) feature vector describing *violations* and *params*."""
        vec = np.zeros(self.FEATURE_DIM, dtype=np.float64)

        # Recompute analytical margins given current params
        try:
            margins = drc_margins(
                float(params.get("w_N",      0.52)),
                float(params.get("w_P",      0.42)),
                float(params.get("l",         0.15)),
                rules,
                gap_y    = float(params.get("gap_y",    _inter_cell_gap(rules))),
                finger_N = float(params.get("finger_N", 1.0)),
                finger_P = float(params.get("finger_P", 1.0)),
            )
        except Exception:
            margins = np.zeros(self.N_RULES)

        # Rule violation magnitudes (negative margin → positive "deficit")
        vec[:self.N_RULES] = np.maximum(0.0, -margins)

        # Current param values
        for i, pname in enumerate(_PARAM_NAMES):
            vec[self.N_RULES + i] = float(params.get(pname, 0.0))

        # Spatial centroid of violations
        if violations:
            xs = [v.x for v in violations if hasattr(v, "x")]
            ys = [v.y for v in violations if hasattr(v, "y")]
            vec[self.N_RULES + self.N_PARAMS]     = float(np.mean(xs)) if xs else 0.0
            vec[self.N_RULES + self.N_PARAMS + 1] = float(np.mean(ys)) if ys else 0.0

        vec[self.N_RULES + self.N_PARAMS + 2] = float(len(violations))

        return vec


# ── Fix dataset ────────────────────────────────────────────────────────────────

class FixDataset(NamedTuple):
    """Training dataset for :class:`DRCFixPredictor`.

    Attributes
    ----------
    X :
        Violation-encoded feature matrix, shape ``(N, 19)``.
    y :
        Parameter delta matrix, shape ``(N, 6)``.
        Column order matches :data:`_PARAM_NAMES`.
    """
    X: np.ndarray
    y: np.ndarray


def generate_fix_dataset(
    rules:     PDKRules,
    n_samples: int = 10_000,
    seed:      int = 42,
) -> FixDataset:
    """Generate analytical violation→fix-delta training pairs.

    For each sample we draw a parameter vector, compute the analytical DRC
    margins, and for each violated rule calculate the minimum delta in the
    primary fix parameter that would bring the margin back to zero.
    The resulting deltas form the regression target ``y``.

    Parameters
    ----------
    rules :
        PDK rules.
    n_samples :
        Number of parameter samples to draw.
    seed :
        NumPy RNG seed.

    Returns
    -------
    FixDataset
    """
    rng = np.random.default_rng(seed)
    enc = ViolationEncoder()

    gap_min = _inter_cell_gap(rules)
    poly_wmin = rules.poly["width_min_um"]
    diff_wmin = rules.diff["width_min_um"]
    c_size    = rules.contacts["size_um"]
    c_enc     = rules.contacts["enclosure_in_diff_um"]
    stp       = rules.contacts["space_to_poly_um"]
    li1_wmin  = rules.li1["width_min_um"]
    nw_enc    = rules.nwell["enclosure_of_pdiff_um"]
    nw_wmin   = rules.nwell["width_min_um"]

    # Sample params biased toward the violating region
    w_N_arr    = rng.uniform(0.08, 0.60, n_samples)
    w_P_arr    = rng.uniform(0.08, 0.60, n_samples)
    l_arr      = rng.uniform(0.08, 0.40, n_samples)
    gap_y_arr  = rng.uniform(0.00, gap_min * 3, n_samples)
    fn_arr     = rng.integers(1, 5, n_samples)
    fp_arr     = rng.integers(1, 5, n_samples)

    X_rows: list[np.ndarray] = []
    y_rows: list[np.ndarray] = []

    for w_N, w_P, l, gap_y, fn, fp in zip(
        w_N_arr, w_P_arr, l_arr, gap_y_arr, fn_arr, fp_arr
    ):
        try:
            margins = drc_margins(
                w_N, w_P, l, rules,
                gap_y=float(gap_y), finger_N=float(fn), finger_P=float(fp),
            )
        except Exception:
            continue

        # Only use samples that have at least one violation
        if np.all(margins >= 0):
            continue

        params = {
            "w_N":      w_N,
            "w_P":      w_P,
            "l":        l,
            "gap_y":    float(gap_y),
            "finger_N": float(fn),
            "finger_P": float(fp),
        }

        # Compute minimum-delta fix for each violated rule
        delta = np.zeros(len(_PARAM_NAMES), dtype=np.float64)

        ng_base = transistor_geom(w_N, l, "nmos", rules)
        pg_base = transistor_geom(w_P, l, "pmos", rules)
        ng = _geom_override_fingers(ng_base, int(fn), rules)
        pg = _geom_override_fingers(pg_base, int(fp), rules)

        for rule_idx, (rule_name, margin) in enumerate(zip(MARGIN_NAMES, margins)):
            if margin >= 0:
                continue
            # deficit = amount the param must change
            deficit = -margin + _EPS
            p_idx = _RULE_FIX_PARAM[rule_name]

            if rule_name == "poly.1":
                # l → increase l
                delta[p_idx] = max(delta[p_idx], deficit)

            elif rule_name == "diff.1_N":
                # w_finger_N = w_N / fn → must reach diff_wmin
                # delta_w_N = deficit * fn
                delta[p_idx] = max(delta[p_idx], deficit * fn)

            elif rule_name == "diff.1_P":
                delta[p_idx] = max(delta[p_idx], deficit * fp)

            elif rule_name in ("licon.5a_N", "licon.7_N", "li1.1"):
                # sd_length is fixed by PDK min; can't fix via params analytically.
                # Widen w_N so transistor_geom recalculates (sd_length is constant
                # in sky130A, so this signals the model to try widening).
                delta[p_idx] = max(delta[p_idx], deficit)

            elif rule_name in ("licon.5a_P", "licon.7_P"):
                delta[p_idx] = max(delta[p_idx], deficit)

            elif rule_name == "diff.2":
                # gap_y → increase gap_y by deficit
                delta[p_idx] = max(delta[p_idx], deficit)

            elif rule_name == "nwell.1":
                # nwell_x_width = total_x_P + 2*nw_enc >= nw_wmin
                # total_x_P = (fp+1)*sd + fp*l  → fix via w_P (changes total_y only, not x)
                # Actually nwell.1 is about X-width of nwell; to increase total_x_P
                # we need more fingers or wider device. Fix via increasing fp:
                # If fp < 4: suggest fp+1 (which increases total_x_P by sd+l)
                # Otherwise widen w_P.
                if fn < 4:
                    delta[5] = max(delta[5], 1.0)  # finger_P += 1
                else:
                    delta[p_idx] = max(delta[p_idx], deficit)

        # Skip if no deltas were computed (shouldn't happen)
        if not np.any(delta > 0):
            continue

        feat = enc.encode([], params, rules)  # no live DRC violations (analytical)
        X_rows.append(feat)
        y_rows.append(delta)

    X = np.array(X_rows, dtype=np.float64)
    y = np.array(y_rows, dtype=np.float64)
    return FixDataset(X=X, y=y)


# ── DRC fix predictor ──────────────────────────────────────────────────────────

class DRCFixPredictor:
    """MLP that maps violation features → parameter deltas.

    Parameters
    ----------
    hidden_layer_sizes :
        Sizes of hidden layers in the MLP (passed to
        ``sklearn.neural_network.MLPRegressor``).

    Usage::

        pred = DRCFixPredictor()
        pred.fit(dataset.X, dataset.y)
        delta = pred.predict(violations, params)
        # delta is {param_name: delta_value, ...}
    """

    def __init__(self, hidden_layer_sizes: tuple[int, ...] = (64, 32)):
        self.hidden_layer_sizes = hidden_layer_sizes
        self._mlp = None
        self._encoder = ViolationEncoder()

    def fit(self, X: np.ndarray, y: np.ndarray) -> "DRCFixPredictor":
        """Train the MLP on violation-encoding → delta pairs.

        Parameters
        ----------
        X :
            Feature matrix from :func:`generate_fix_dataset`, shape ``(N, 19)``.
        y :
            Delta matrix, shape ``(N, 6)``.

        Returns
        -------
        self
        """
        try:
            from sklearn.neural_network import MLPRegressor
            from sklearn.preprocessing  import StandardScaler
            from sklearn.pipeline       import Pipeline
        except ImportError as exc:
            raise ImportError(
                "scikit-learn is required to train DRCFixPredictor.  "
                "Install it with: pip install scikit-learn"
            ) from exc

        self._mlp = Pipeline([
            ("scaler", StandardScaler()),
            ("mlp",    MLPRegressor(
                hidden_layer_sizes=self.hidden_layer_sizes,
                max_iter=500,
                random_state=42,
            )),
        ])
        self._mlp.fit(X, y)
        return self

    def predict(
        self,
        violations: list,   # list[DRCViolation]
        params:     dict,
        rules:      PDKRules,
    ) -> dict[str, float]:
        """Predict parameter deltas that should fix *violations*.

        Parameters
        ----------
        violations :
            DRC violations from the last synthesis attempt.
        params :
            Current parameter dict.
        rules :
            PDK rules (used for analytical margin recomputation).

        Returns
        -------
        dict[str, float]
            Map of ``param_name → delta``.  Zero for params not needing change.
            Returns zeros for all params if the model is not trained.
        """
        if self._mlp is None:
            return {p: 0.0 for p in _PARAM_NAMES}

        feat = self._encoder.encode(violations, params, rules)
        delta_vec = self._mlp.predict(feat.reshape(1, -1))[0]

        # Clamp deltas to non-negative (we only fix, never shrink)
        delta_vec = np.maximum(0.0, delta_vec)

        result: dict[str, float] = {}
        for i, pname in enumerate(_PARAM_NAMES):
            val = float(delta_vec[i])
            if val != 0.0:
                result[pname] = val
        return result

    @property
    def is_trained(self) -> bool:
        """True if the predictor has been fitted."""
        return self._mlp is not None

    def __repr__(self) -> str:
        status = "trained" if self.is_trained else "not trained"
        return f"DRCFixPredictor(hidden={self.hidden_layer_sizes}, {status})"
